name: Ansible Playbook Deployment

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Uninstall System Ansible
        run: |
          sudo apt remove -y ansible
          sudo apt autoremove -y

      - name: Install Python and Pip
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

      - name: Install Ansible via pip
        run: |
          python3 -m pip install --upgrade pip
          pip install "ansible-core==2.18.1"
          pip install "ansible"

      - name: Install Ansible Lint
        run: |
          pip install ansible-lint

      - name: Verify Ansible Version
        run: |
          ansible --version
          python3 -c "import ansible; print(ansible.__version__)"

      - name: Lint Ansible Playbook
        run: ansible-lint https://github.com/AdmineLaura/container_lab2/blob/main/configure_all_hosts.yml

      - name: Check Ansible Playbook Syntax
        run: ansible-playbook --syntax-check https://github.com/AdmineLaura/container_lab2/blob/main/configure_all_hosts.yml
