name: Lint

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
      
jobs:      
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Install python dependencies
        run: pip install flake8 pylint
        
      - name: Lint with flake8
        run: |
            flake8 . --count --select-E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        

   
