name: Ansible Playbook Deployment

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible=22.16.3

      - name: Install Ansible Lint
        run: pip install ansible-lint

      - name: Lint Ansible Playbook
        run: ansible-lint configure_all_hosts.yml

      - name: Check Ansible Playbook Syntax
        run: ansible-playbook --syntax-check configure_all_hosts.yml
